apiVersion: v1
kind: Service
metadata:
  name: argocd-pythonapp-todo
  labels:
    app: argocd-pythonapp-todo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  type: LoadBalancer
  selector:
    app: argocd-pythonapp-todo
